#!python2

from sys import exit

userName = str(raw_input('What is your name? '))

def start():
    if userName != 'Mez':
        print "\n\tReally? That's your name? Ok then..."
        story()
    elif userName == "Mez":
        print "Mine too! COOL!"
        story()
    else:
        exit(0)
        
def story():
    print ''' # do triple ticks for multi-line strings
    Our hero awakens in a dense fog. He struggles to get his bearings 
    as his senses are battered by unfamiliar shapes and sounds. 
    He starts to panic. He feels a scream in his throat when he
    suddenly realizes he's on his couch and his roomate has left the 
    fog machine on again.'''
    
start()
